### ISSUE TITLE
LoRA setMode Overwrite to 0 on Init Object Lora 

### ISSUE THREAD

**Issue by KachPro** [raspberrypi-tw/lora-sx1276#1]
/opt/GW-Lorawan/lora-sx1276/SX127x/board_config.py:58: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(BOARD.LED, GPIO.OUT)
128  --> SLEEP MODE
1      --> FSK_STDBY
0      --> ?????????
Traceback (most recent call last):
  File "lora_forwarder.py", line 119, in <module>
    lora = LoRaSocket(verbose=False)
  File "lora_forwarder.py", line 83, in __init__
    super(LoRaSocket, self).__init__(verbose)
  File "/opt/GW-Lorawan/lora-sx1276/SX127x/LoRa.py", line 101, in __init__
    self.rx_chain_calibration(calibration_freq)
  File "/opt/GW-Lorawan/lora-sx1276/SX127x/LoRa.py", line 858, in rx_chain_calibration
    self.set_freq(freq_bkup)
  File "/opt/GW-Lorawan/lora-sx1276/SX127x/LoRa.py", line 284, in set_freq
    assert self.mode == MODE.SLEEP or self.mode == MODE.STDBY or self.mode == MODE.FSK_STDBY
AssertionError

**Comment by Jaumehrt99** [comment]
Hi!

I have the same error! How did you fix it?

Thanks!
